### ISSUE TITLE
NotImplementedError: [] not recognized

### ISSUE THREAD

**Issue by CLOT-SALUTE** [Bohao-Lee/CME#6]
Traceback (most recent call last):
  File "/backup1/S320080026/Fewshot_Detection-master/train_meta.py", line 114, in <module>
    test_metaset = dataset.MetaDataset(metafiles=metadict, train=True)
  File "/backup1/S320080026/Fewshot_Detection-master/dataset.py", line 323, in __init__
    raise NotImplementedError('{} not recognized'.format(pair))
NotImplementedError: [] not recognized

I can't find this error,can you help me

**Comment by Bohao-Lee** [comment]
> Traceback (most recent call last):
> File "/backup1/S320080026/Fewshot_Detection-master/train_meta.py", line 114, in
> test_metaset = dataset.MetaDataset(metafiles=metadict, train=True)
> File "/backup1/S320080026/Fewshot_Detection-master/dataset.py", line 323, in **init**
> raise NotImplementedError('{} not recognized'.format(pair))
> NotImplementedError: [] not recognized
> 
> I can't find this error,can you help me

I have never met this error before. Can you recheck whether the data is prepared correctly?

**Comment by kobemaker** [comment]
> 回溯（最近一次调用）：文件 “/backup1/S320080026/Fewshot_Detection-master/train_meta.py”，第 114 行，在 test_metaset = 数据集中。MetaDataset（metafiles=metadict， train=True） File “/backup1/S320080026/Fewshot_Detection-master/dataset.py”，第 323 行，在 **init** 中引发 NotImplementError（'{} not recognized'.format（pair）） NotImplementError： [] 无法识别
> 
> 我找不到此错误，你能帮我吗

我也遇到了类似的问题，请问您是如何解决的
